run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - goconst
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  gosec:
    excludes:
      - G204 # subprocess launched with variable - expected for xcodebuild

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
